services:
  postgres-crawler:
    image: postgres:15-alpine
    container_name: crawler_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crawler_data
    ports:
      - "5432:5432"

  postgres-llm:
    image: pgvector/pgvector:pg15
    container_name: llm_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: llm_data
    ports:
      - "5433:5432"

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: crawler_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "web_pages_raw:1:1" # Сразу создаст топик
    depends_on:
      - zookeeper
